import React, { useEffect, useState } from 'react';
import { apiPost, apiGet } from './api';
import logo from '/logo.png';
export default function App() {
const [user,setUser]=useState(null); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(false);
const [students,setStudents]=useState([]); const [staff,setStaff]=useState([]); const [payments,setPayments]=useState([]); const [schedule,setSchedule]=useState([]);
useEffect(()=>{const saved=localStorage.getItem('ssbUser'); if(saved){setUser(JSON.parse(saved)); loadDashboard();}},[]);
async function handleLogin(){setLoading(true); const res=await apiPost({action:'login',username,password}); if(res.status){setUser(res.user); localStorage.setItem('ssbUser',JSON.stringify(res.user)); await loadDashboard();} else {alert('Username / Password salah');} setLoading(false);}
async function loadDashboard(){setStudents(await apiGet('getStudents')||[]);setStaff(await apiGet('getStaff')||[]);setPayments(await apiGet('getPayments')||[]);setSchedule(await apiGet('getSchedule')||[]);}
function logout(){localStorage.removeItem('ssbUser'); window.location.reload();}
if(!user){return <div className='login-page'><div className='login-box'><img src={logo} className='logo'/><h2>SSB SWADAYA FC LOGIN</h2><input placeholder='Username' value={username} onChange={e=>setUsername(e.target.value)}/><input type='password' placeholder='Password' value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={handleLogin}>{loading?'LOADING...':'LOGIN'}</button></div></div>}
return <div className='app-shell'><aside className='sidebar'><div className='brand'><img src={logo} className='side-logo'/><h2>SWADAYA FC</h2></div><ul className='menu'><li>🏠 Dashboard</li><li>👦 Students</li><li>👔 Staff</li><li>💳 Payments</li><li>📅 Attendance</li><li>🗓 Schedule</li><li onClick={logout}>🚪 Logout</li></ul></aside><main className='main-content'><header className='top-header'><h1>SSB SWADAYA FC MANAGEMENT SYSTEM</h1><p>Welcome back, {user.name}</p></header><section className='cards'><div className='card blue'><h3>Total Students</h3><p>{students.length}</p></div><div className='card green'><h3>Total Staff</h3><p>{staff.length}</p></div><div className='card orange'><h3>Total Payments</h3><p>{payments.length}</p></div><div className='card purple'><h3>Total Schedule</h3><p>{schedule.length}</p></div></section></main></div>}
}