import React, { useState } from 'react';
import './App.css';
const logo='https://i.ibb.co/6JQp8fH/SwadayaFC-logo.png';
export default function App(){const [page,setPage]=useState('login');
const students=[{id:'SWD001',name:'Andi Saputra',group:'U12',parent:'Bpk Joko'},{id:'SWD002',name:'Rizky Maulana',group:'U12',parent:'Bpk Ahmad'}];
const payments=[{name:'Andi Saputra',amount:'Rp150.000',status:'Lunas'}];
if(page==='login') return <LoginPage setPage={setPage}/>;
if(page==='ortu') return <ParentPortal setPage={setPage} students={students} payments={payments}/>;
return <AdminDashboard setPage={setPage} students={students} payments={payments}/>;}
function LoginPage({setPage}){return <div className='loginWrap'><div className='loginCard'><img src={logo} alt='logo' className='clubLogo'/><h1>SSB SWADAYA FC</h1><p>Football Academy Management System Premium</p><button onClick={()=>setPage('admin')}>LOGIN ADMIN</button><button onClick={()=>setPage('ortu')}>LOGIN ORANG TUA</button></div></div>;}
function AdminDashboard({setPage,students,payments}){return <div className='appShell'><aside className='sidebar'><img src={logo} alt='logo' className='sideLogo'/><h2>SSB SWADAYA FC</h2><nav><div>Dashboard</div><div>Data Siswa</div><div>Absensi</div><div>Pembayaran</div></nav><button className='logoutBtn' onClick={()=>setPage('login')}>Logout</button></aside><main className='mainContent'><div className='hero'><h1>Selamat Datang, Admin!</h1></div><div className='statsGrid'><div className='statBox'><h3>{students.length}</h3><span>Total Siswa</span></div><div className='statBox'><h3>12</h3><span>Hadir Hari Ini</span></div><div className='statBox'><h3>Rp25.000.000</h3><span>Kas Bulan Ini</span></div><div className='statBox'><h3>6</h3><span>Tunggakan</span></div></div><div className='panel'><h3>Status Pembayaran</h3>{payments.map((p,i)=><div className='row' key={i}>{p.name} - {p.amount} - {p.status}</div>)}</div></main></div>;}
function ParentPortal({setPage,students,payments}){const student=students[0];return <div className='loginWrap'><div className='parentCard'><img src={logo} alt='logo' className='clubLogoSmall'/><h1>PORTAL ORANG TUA</h1><h2>{student.name}</h2><p>{payments[0].amount} - {payments[0].status}</p><button onClick={()=>setPage('login')}>Kembali</button></div></div>;}